[supervisord]
nodaemon=true
user=root

[program:vnc]
command=/bin/bash -c "su - ubuntu -c 'vncserver :1 -geometry 1280x800 -depth 24 && tail -f /home/ubuntu/.vnc/*.log'"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:novnc]
command=/usr/bin/websockify --verbose --web=/usr/share/novnc 8080 localhost:5901
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
